# 총 누계거리는 테이블 내 존재하는 역들의 역 사이 거리의 총 합

SELECT
    ROUTE,
    CONCAT(ROUND(SUM(D_BETWEEN_DIST),1), 'km') AS TOTAL_DISTANCE,
    CONCAT(ROUND(AVG(D_BETWEEN_DIST),2), 'km') AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE, LINE
ORDER BY ROUND(SUM(D_BETWEEN_DIST), 1) DESC;