SELECT
    MCDP_CD AS 진료과코드,
    COUNT(DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05') AS '5월예약건수'
FROM APPOINTMENT
WHERE DATE_FORMAT(APNT_YMD, '%Y-%m') = '2022-05'
GROUP BY 진료과코드
ORDER BY COUNT(PT_NO) ASC, MCDP_CD ASC;