-- 코드를 입력하세요
SELECT
    B.INGREDIENT_TYPE,
    SUM(A.TOTAL_ORDER) AS INGREDIENT_TYPE
FROM FIRST_HALF A
INNER JOIN ICECREAM_INFO B
ON A.FLAVOR = B.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER ASC;